whitelist_rules:
  - anyobject_protocol # lint
  - closing_brace # style
  - closure_end_indentation # style
  - closure_spacing # style
  - colon # style
  - comma # style
  - control_statement # style
  - empty_enum_arguments # style
  - empty_parameters # style
  - empty_parentheses_with_trailing_closure # style
  - explicit_init # idiomatic
  - implicit_return # style
  - joined_default_parameter # idiomatic
  - leading_whitespace # style
  - legacy_cggeometry_functions # idiomatic
  - legacy_constant # idiomatic
  - legacy_constructor # idiomatic
  - legacy_nsgeometry_functions # idiomatic
  - literal_expression_end_indentation # style
  - mark # lint
  - modifier_order # style
  - no_space_in_method_call # style
  - number_separator # style
  - opening_brace # style
  - operator_usage_whitespace # style
  - prefer_self_type_over_type_of_self # style
  - prefer_zero_over_explicit_init # idiomatic
  - protocol_property_accessors_order # style
  - redundant_discardable_let # style
  - redundant_nil_coalescing # idiomatic
  - redundant_objc_attribute # idiomatic
  - redundant_optional_initialization # idiomatic
  - redundant_type_annotation # idiomatic
  - redundant_void_return # idiomatic
  - return_arrow_whitespace # style
  - sorted_imports # style
  - statement_position # style
  - syntactic_sugar # idiomatic
  - toggle_bool # idiomatic
  - trailing_comma # style
  - trailing_newline # style
  - trailing_semicolon # idiomatic
  - trailing_whitespace # style
  - unneeded_parentheses_in_closure_argument # style
  - untyped_error_in_catch # idiomatic
  - unused_closure_parameter # lint
  - unused_control_flow_label # lint
  - unused_import # lint
  - vertical_whitespace # style
  - vertical_whitespace_between_cases # style
  - vertical_whitespace_closing_braces # style
  - vertical_whitespace_opening_braces # style
  - void_return # style